### ISSUE TITLE
png files have colours inverted

### ISSUE THREAD

**Issue by slgardiner** [NicklasVraa/Obsidian-academic-export#4]
Firstly: I love this, thank you so much!

Issue:
Exporting to pdf is inverting the colours of my inserted png files, I'm not sure why this is happening or how to fix, any help would be appreciated!

**Comment by NicklasVraa** [comment]
I use color-inversion for my figures, because my obsidian theme is dark (and so looks right with light figures), but the pdf is light (and so looks right with dark figures).

Anyways, I removed the inversion. You can also just comment out `filter: invert(100%) !important;` in the snippet file :)
