### ISSUE TITLE
label and ref

### ISSUE THREAD

**Issue by slgardiner** [NicklasVraa/Obsidian-academic-export#5]
Is it possible to label a particular line or equation and then reference it later to get the correct numbering, which auto updates when the md is compiled into tex? In Latex I would use 
``` \label{test}```
then
```\ref{test}```
but these show up explicitly in the final pdf instead of the label itself.

thanks again for the amazing tool!

**Comment by NicklasVraa** [comment]
I am not aware of any way to to this with just css. If you know of a way, please feel free to submit a pull request.

Maybe you would be interested in [this project](https://github.com/NicklasVraa/Latex-academic-class), which I made to address these limitations. Thank you for the kind words :)

**Comment by slgardiner** [comment]
no worries, thanks for the quick response!
