### ISSUE TITLE
New environments

### ISSUE THREAD

**Issue by slgardiner** [NicklasVraa/Obsidian-academic-export#6]
Is it possible to have an environment, similar to Latex 

``` 
\begin{environment}
    blah blah
\end{environment} 
```

In particular when writing maths I would like to be able to have a theorem and proof environment for example (perhaps even with the proof environment giving a small square at the end like in the Latex amsmath package). any help would be greatly appreciated and thanks once again for the amazing tool!

**Comment by NicklasVraa** [comment]
I don't know, if the markdown is ever converted into TeX. I'm pretty sure, that obsidian simply renders a pdf, much like if you print a webpage in your browser. The math is handled by mathjax.

Maybe you would be interested in [this project](https://github.com/NicklasVraa/Latex-academic-class), which I made to address these limitations. Once again, thank you for the kind words :)

**Comment by slgardiner** [comment]
no worries, thanks for the quick response!
